ManageBook/Models/EntryViewModels.cs
using ManageBookModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace ManageBook.Models
{
    public class EntryIndexViewModel
    {
        public IList<Entry> Entries { get; set; }
        public List<ApplicationUser> Users { get; set; }
        public List<Project> Projects { get; set; }
    }
}

ManageBook/Controllers/EntryController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ManageBook.Models;
using ManageBookModels;

namespace ManageBook.Controllers
{
    public class EntryController : Controller
    {
        //private ManageBookContext db = new ManageBookContext();

        // GET: Entry
        public ActionResult Index(int? id)
        {
            using(var db = new ApplicationDbContext())
            {
                ViewBag.Users = db.Users.ToList();
            }
            using(var db = new ManageBookContext())
            {
                ViewBag.Projects = db.Projects.ToList();
                return View(db.Entries.ToList());
            }
        }

        // GET: Entry/Details/5
        public ActionResult Details(int? id)
        {
            using (var db = new ManageBookContext())
            {
                if (id == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }
                Entry entry = db.Entries.Find(id);
                ViewBag.Projects = db.Projects.ToList();
                if (entry == null)
                {
                    return HttpNotFound();
                }
                return View(entry);
            }
        }

        // GET: Entry/Create
        public ActionResult Create()
        {
            using(var db = new ApplicationDbContext())
            {
                ViewBag.Users = db.Users.ToList();
            }
            using (var db = new ManageBookContext())
            {
                ViewBag.Projects = db.Projects.ToList();
            }
            return View();
        }

        // POST: Entry/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Priority,Description,Information,UserId,Date,InvoicableHours,ActualHours,Invoiced,ProjectId")] Entry entry)
        {
            if (ModelState.IsValid)
            {
                using (var db = new ManageBookContext())
                {
                    db.Entries.Add(entry);
                    db.SaveChanges();
                }
                return RedirectToAction("Index");
            }

            return View(entry);
        }

        // GET: Entry/Edit/5
        public ActionResult Edit(int? id)
        {
            using (var db = new ManageBookContext())
            {
                if (id == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }
                Entry entry = db.Entries.Find(id);
                if (entry == null)
                {
                    return HttpNotFound();
                }
                return View(entry);
            }
        }

        // POST: Entry/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Priority,Description,Information,UserId,Date,InvoicableHours,ActualHours,Invoiced,ProjectId")] Entry entry)
        {
            if (ModelState.IsValid)
            {
                using (var db = new ManageBookContext())
                {
                    db.Entry(entry).State = EntityState.Modified;
                    db.SaveChanges();
                }
                return RedirectToAction("Index");
            }
            return View(entry);
        }

        // GET: Entry/Delete/5
        public ActionResult Delete(int? id)
        {
            using (var db = new ManageBookContext())
            {
                if (id == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }
                Entry entry = db.Entries.Find(id);
                if (entry == null)
                {
                    return HttpNotFound();
                }
                return View(entry);
            } 
        }

        // POST: Entry/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            using (var db = new ManageBookContext())
            {
                Entry entry = db.Entries.Find(id);
                db.Entries.Remove(entry);
                db.SaveChanges();
            }
            return RedirectToAction("Index");
        }

        public ActionResult Filter(string project, string user)
        {

            if((project == null || project.Equals("")) && (user == null || user.Equals("")))
            {
                return RedirectToAction("Index");
            }
            //else if(project == null && user != null)
            //{

            //}
            else
            {
                if(!project.Equals("") && user.Equals(""))
                {
                    var projectid = Int32.Parse(project);

                    using (var db = new ApplicationDbContext())
                    {
                        ViewBag.Users = db.Users.ToList();
                    }

                    using (var db = new ManageBookContext())
                    {
                        ViewBag.Projects = db.Projects.ToList();
                        List<Entry> entries = db.Entries.Where(x => x.ProjectId == projectid).ToList();
                        if (entries == null)
                        {
                            return HttpNotFound();
                        }
                        return View("Index", entries);
                    }
                }
                else if (project.Equals("") && !user.Equals(""))
                {
                    using (var db = new ApplicationDbContext())
                    {
                        ViewBag.Users = db.Users.ToList();
                    }

                    using (var db = new ManageBookContext())
                    {
                        ViewBag.Projects = db.Projects.ToList();
                        List<Entry> entries = db.Entries.Where(x => x.UserId == user).ToList();
                        if (entries == null)
                        {
                            return HttpNotFound();
                        }
                        return View("Index", entries);
                    }
                }
                else
                {
                    var projectid = Int32.Parse(project);

                    using (var db = new ApplicationDbContext())
                    {
                        ViewBag.Users = db.Users.ToList();
                    }

                    using (var db = new ManageBookContext())
                    {
                        ViewBag.Projects = db.Projects.ToList();
                        List<Entry> entries = db.Entries.Where(x => x.ProjectId == projectid && x.UserId == user).ToList();
                        if (entries == null)
                        {
                            return HttpNotFound();
                        }
                        return View("Index", entries);
                    }
                }
            }
        }

        //public ActionResult Filter(int? id)
        //{
        //    using (var db = new ManageBookContext())
        //    {
        //        if (id == null)
        //        {
        //            return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
        //        }
        //        List<Entry> entries = db.Entries.Where(x => x.ProjectId == id).ToList();
        //        if (entries == null)
        //        {
        //            return HttpNotFound();
        //        }
        //        return View("Index", entries);
        //    }
        //}

        /*protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }*/
    }
}

ManageBook/Views/Entry/Create.cshtml
@model ManageBookModels.Entry

@{
    ViewBag.Title = "Create";
    var projects = ViewBag.Projects;
    var users = ViewBag.Users;

    var listUsers = new List<SelectListItem>();
    foreach(var user in users)
    {
        listUsers.Add(new SelectListItem() { Text = user.UserName, Value = user.Id.ToString() });
    }

    var listProjects = new List<SelectListItem>();
    foreach (var project in projects)
    {
        listProjects.Add(new SelectListItem() { Text = project.Name, Value = project.Id.ToString() });
    }
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Entry</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="form-group">
            @Html.LabelFor(model => model.Priority, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @*@Html.EditorFor(model => model.Priority, new { htmlAttributes = new { @class = "form-control" } })*@
                @{
                    var listPriorities = new SelectListItem[]{
                        new SelectListItem() {Text = "X", Value="0"},
                        new SelectListItem() {Text = "1", Value="1"},
                        new SelectListItem() {Text = "2", Value="2"},
                        new SelectListItem() {Text = "3", Value="3"},
                        new SelectListItem() {Text = "!!!", Value="4"}
                    };
                }
                @Html.DropDownListFor(model => model.Priority, listPriorities, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Priority, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, "To Do", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.UserId, "Who", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.UserId, listUsers, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.UserId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ProjectId, "Project", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.ProjectId, listProjects, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ProjectId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Date, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Date, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Date, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Information, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Information, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Information, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.InvoicableHours, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.InvoicableHours, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.InvoicableHours, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ActualHours, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ActualHours, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ActualHours, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Invoiced, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.Invoiced)
                    @Html.ValidationMessageFor(model => model.Invoiced, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

ManageBook/Views/Entry/Delete.cshtml
@model ManageBookModels.Entry

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Entry</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Priority)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Priority)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Information)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Information)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.UserId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UserId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Date)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Date)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.InvoicableHours)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.InvoicableHours)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ActualHours)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ActualHours)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Invoiced)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Invoiced)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

ManageBook/Views/Entry/Details.cshtml
@using ManageBook.Models;
@model ManageBookModels.Entry

@{
    ViewBag.Title = "Details";

    var user = new ApplicationUser();
    using (var db = new ApplicationDbContext())
    {
        user = db.Users.Find(Model.UserId);
    }

    var projects = ViewBag.Projects;

    var listProjects = new List<SelectListItem>();
    foreach (var project in projects)
    {
        listProjects.Add(new SelectListItem() { Text = project.Name, Value = project.Id.ToString() });
    }
}

<h2>Details</h2>

<div>
    <h4>Entry</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayName("Project")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Project.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Priority)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Priority)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Information)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Information)
        </dd>

        <dt>
            @Html.DisplayName("Who")
        </dt>

        <dd>
            @*@Html.DisplayFor(model => model.UserId)*@
            @user.UserName
            @*@Html.DisplayFor(model => model.User.UserName)*@
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Date)
        </dt>

        <dd>
            @*@Html.DisplayFor(model => model.Date)*@
            @Model.Date.ToString("MM/dd/yyyy")
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.InvoicableHours)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.InvoicableHours)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ActualHours)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ActualHours)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Invoiced)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Invoiced)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

ManageBook/Views/Entry/Edit.cshtml
@model ManageBookModels.Entry

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Entry</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Priority, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Priority, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Priority, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Information, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Information, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Information, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.UserId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.UserId, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.UserId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Date, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Date, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Date, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.InvoicableHours, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.InvoicableHours, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.InvoicableHours, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ActualHours, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ActualHours, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ActualHours, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Invoiced, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.Invoiced)
                    @Html.ValidationMessageFor(model => model.Invoiced, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

ManageBook/Views/Entry/Index - Copy.cshtml
@using ManageBook.Models;

@model IList<ManageBookModels.Entry>

@{
    ViewBag.Title = "Index";

    var projects = ViewBag.Projects;
    var users = ViewBag.Users;

    var listUsers = new List<SelectListItem>();
    foreach (var user in users)
    {
        listUsers.Add(new SelectListItem() { Text = user.UserName, Value = user.Id.ToString() });
    }

    var listProjects = new List<SelectListItem>();
    foreach (var project in projects)
    {
        listProjects.Add(new SelectListItem() { Text = project.Name, Value = project.Id.ToString() });
    }
}

@*<h2>Index</h2>*@

<table class="table">
    <tr>
        <th></th>
        <th></th>
        <th></th>
    </tr>
    @using (Html.BeginForm("Filter", "Entry", FormMethod.Post))
    {
        <tr>
            <td>
                @Html.DropDownList("project", listProjects, "All", new { @class = "form-control" })
            </td>
            <td>
                @Html.DropDownList("user", listUsers, "All", new { @class = "form-control" })
            </td>
            <td>
                <input type="submit" value="Filter" class="btn btn-default" />
            </td>
        </tr>
    }
</table>

<table class="table">
    <tr>
        <th>
            @Html.DisplayName("Priority")
        </th>
        <th>
            @Html.DisplayName("To Do")
        </th>
        @*<th>
            @Html.DisplayNameFor(model => model.Information)
        </th>*@
        <th>
            @Html.DisplayName("Who")
        </th>
        <th>
            @Html.DisplayName("Project")
        </th>
        <th>
            @Html.DisplayName("Date")
        </th>
        <th>
            @Html.DisplayName("Hours Invoicable")
        </th>
        <th>
            @Html.DisplayName("Hours Actual")
        </th>
        <th>
            @Html.DisplayName("Invoiced")
        </th>
        <th></th>
    </tr>

@foreach (var item in Model)
{
    using (Html.BeginForm("Edit", "Entry", FormMethod.Post))
    {
        @Html.AntiForgeryToken()
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(m => m.First(x => x.Id == item.Id).Id)
        <tr>
            <td>
                @{
                    var listPriorities = new SelectList(new List<SelectListItem>
                    {
                        new SelectListItem() {Text = "X", Value="0"},
                        new SelectListItem() {Text = "1", Value="1"},
                        new SelectListItem() {Text = "2", Value="2"},
                        new SelectListItem() {Text = "3", Value="3"},
                        new SelectListItem() {Text = "!!!", Value="4"}
                    },
                    "Value", // property to be set as Value of dropdown item
                    "Text",  // property to be used as text of dropdown item
                    item.Priority.ToString());
                }
                @Html.DropDownListFor(m => m.First(x => x.Id == item.Id).Priority, listPriorities, new { @class = "form-control" })
                @Html.ValidationMessageFor(m => m.First(x => x.Id == item.Id).Priority, "", new { @class = "text-danger" })
            </td>
            <td>
                @*@Html.DisplayFor(modelItem => item.Description)*@
                @Html.EditorFor(m => m.First(x => x.Id == item.Id).Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(m => m.First(x => x.Id == item.Id).Description, "", new { @class = "text-danger" })
            </td>
            @*<td>
                @Html.DisplayFor(modelItem => item.Information)
            </td>*@
            <td>
                @{
                    var dropdownUsers = new SelectList(listUsers,
                                        "Value", // property to be set as Value of dropdown item
                                        "Text",  // property to be used as text of dropdown item
                                        item.UserId.ToString());
                }
                @Html.DropDownListFor(m => m.First(x => x.Id == item.Id).UserId, dropdownUsers, new { @class = "form-control" })
                @Html.ValidationMessageFor(m => m.First(x => x.Id == item.Id).UserId, "", new { @class = "text-danger" })
            </td>
            <td>
                @*@Html.DisplayFor(modelItem => item.ProjectId)*@
                @{
                    var dropdownProjects = new SelectList(listProjects,
                    "Value", // property to be set as Value of dropdown item
                    "Text",  // property to be used as text of dropdown item
                    item.ProjectId.ToString());
                }
                @Html.DropDownListFor(m => m.First(x => x.Id == item.Id).ProjectId, dropdownProjects, new { @class = "form-control" })
                @Html.ValidationMessageFor(m => m.First(x => x.Id == item.Id).ProjectId, "", new { @class = "text-danger" })
            </td>
            <td class="form-group">
                @*@Html.ValueFor(modelItem => item.Date, "{0:MM/dd/yyyy}")*@
                @Html.EditorFor(m => m.First(x => x.Id == item.Id).Date,new { htmlAttributes = new { @class = "form-control"@*, @Value = item.Date.ToString("MM/dd/yyyy")*@ } })
                @Html.ValidationMessageFor(m => m.First(x => x.Id == item.Id).Date, "", new { @class = "text-danger" })
            </td>
            <td>
                @*@Html.DisplayFor(modelItem => item.InvoicableHours)*@
                @Html.EditorFor(m => m.First(x => x.Id == item.Id).InvoicableHours, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(m => m.First(x => x.Id == item.Id).InvoicableHours, "", new { @class = "text-danger" })
            </td>
            <td>
                @*@Html.DisplayFor(modelItem => item.ActualHours)*@
                @Html.EditorFor(m => m.First(x => x.Id == item.Id).ActualHours, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(m => m.First(x => x.Id == item.Id).ActualHours, "", new { @class = "text-danger" })
            </td>
            <td>
                @*@Html.DisplayFor(modelItem => item.Invoiced)*@
                @Html.EditorFor(m => m.First(x => x.Id == item.Id).Invoiced)
                @Html.ValidationMessageFor(m => m.First(x => x.Id == item.Id).Invoiced, "", new { @class = "text-danger" })
            </td>
            <td>
                @*@Html.ActionLink("Edit", "Edit", new { id = item.Id })*@
                <input type="submit" value="Save" class="btn btn-default" />
                @Html.ActionLink("Details", "Details", new { id = item.Id }, new { @class = "btn btn-default" })
                @Html.ActionLink("Delete", "Delete", new { id = item.Id }, new { @class = "btn btn-default" })
            </td>
        </tr>
    }
}

</table>

<p>
    @Html.ActionLink("Create New", "Create")
</p>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}